# Generated by Django 3.2.5 on 2021-07-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210706_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ttitle',
            new_name='title',
        ),
    ]
